# Generated by Django 5.0.3 on 2024-03-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_comment_remove_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_of_guests',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
