# Generated by Django 5.0.3 on 2024-03-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title',
        ),
    ]
